// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokedex.Model;

namespace Pokedex.Model.Migrations
{
    [DbContext(typeof(PokemonDbContext))]
    [Migration("20211125130932_InitialPokemonDb")]
    partial class InitialPokemonDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21");

            modelBuilder.Entity("Pokedex.Model.PokeApi.Moves", b =>
                {
                    b.Property<int>("Id_Moves")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MoveId_PropertiesMove")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PokemonDbId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_Moves");

                    b.HasIndex("MoveId_PropertiesMove");

                    b.HasIndex("PokemonDbId");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("Pokedex.Model.PokeApi.PropertiesMove", b =>
                {
                    b.Property<int>("Id_PropertiesMove")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_PropertiesMove");

                    b.ToTable("PropertiesMove");
                });

            modelBuilder.Entity("Pokedex.Model.PokemonDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbilitiesSlotOne")
                        .HasColumnType("TEXT");

                    b.Property<string>("AbilitiesSlotTwo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseExperience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("SpecialAttackense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpritesFrontDefault")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpritesOfficialArtwork")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeOne")
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("Pokedex.Model.PokeApi.Moves", b =>
                {
                    b.HasOne("Pokedex.Model.PokeApi.PropertiesMove", "Move")
                        .WithMany()
                        .HasForeignKey("MoveId_PropertiesMove");

                    b.HasOne("Pokedex.Model.PokemonDb", null)
                        .WithMany("Moves")
                        .HasForeignKey("PokemonDbId");
                });
#pragma warning restore 612, 618
        }
    }
}
